services:
  resource-db:
    image: postgres:17-alpine
    container_name: resource-db
    environment:
      POSTGRES_DB: ${RESOURCE_POSTGRES_DB}
      POSTGRES_USER: ${RESOURCE_POSTGRES_USER}
      POSTGRES_PASSWORD: ${RESOURCE_POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts/resource-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  song-db:
    image: postgres:17-alpine
    container_name: song-db
    environment:
      POSTGRES_DB: ${SONG_POSTGRES_DB}
      POSTGRES_USER: ${SONG_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SONG_POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - ./init-scripts/song-db/init.sql:/docker-entrypoint-initdb.d/init.sql

  song-service:
    build: ./song-service/
    container_name: song-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://song-db:5432/${SONG_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${SONG_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${SONG_POSTGRES_PASSWORD}
      SPRING_SERVER_PORT: ${SONG_SPRING_SERVER_PORT}
    ports:
      - "${SONG_SPRING_SERVER_PORT}:${SONG_SPRING_SERVER_PORT}"
    depends_on:
      - song-db

  resource-service:
    build: ./resource-service/
    container_name: resource-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://resource-db:5432/${RESOURCE_POSTGRES_DB}
      SPRING_DATASOURCE_USERNAME: ${RESOURCE_POSTGRES_USER}
      SPRING_DATASOURCE_PASSWORD: ${RESOURCE_POSTGRES_PASSWORD}
      SPRING_SERVER_PORT: ${RESOURCE_SPRING_SERVER_PORT}
      SPRING_SONG_SERVICE_URL: http://song-service:${SONG_SPRING_SERVER_PORT}
    ports:
      - "${RESOURCE_SPRING_SERVER_PORT}:${RESOURCE_SPRING_SERVER_PORT}"
    depends_on:
      - resource-db